### ISSUE TITLE
freighter login not working (Google Chrome 108.0)

### ISSUE THREAD

**Issue by AmitAronovitch** [stellarterm/stellarterm#1017]
When clicking the "Freighter" button in the Login page, a message pops up saying:
```
Freighter extension is not supported by your browser.
Please use Google Chrome.
```
But the browser IS actually Google Chrome. I believe that this started happening since the upgrade of Chrome to latest release  (so stellarterm no longer recognizes up-to-date Chrome (>=108 ?) as Chrome browser).

## Some further details

In lib/BrowserSupport.js:
```
export function isChrome() { return !!window.chrome && (!!window.chrome.webstore || !!window.chrome.runtime); }
```
But testing in the console, I see that the `chrome` object does not have either `webstore` or `runtime` attributes (probably it did in older versions).

Disabling this test (forcing it to return True) actually causes `stellarterm` to start working (did not encounter any issue so far).

I am not sure which Browser-spefic features (if any) the app is using , so I am not sure why it tested for these properties in the first place (so I cannot offer a safe patch myself at this point).

**Comment by AmitAronovitch** [comment]
BTW: If I disable the browser test completely, it works fine on Firefox as well.

Maybe we can remove it entirely, and replace it with a non-blocking recommendation instead? ("Unsupported browser:if you are experiencing problems, please use one of these instead: ...")

**Comment by AmitAronovitch** [comment]
update: looks like @shiny-mountain already has a fix in staging branch, thanks! :ok_hand:

**Comment by shiny-mountain** [comment]
@AmitAronovitch the fix is already in master
