### ISSUE TITLE
Linting is inactive

### ISSUE THREAD

**Issue by janclarin** [stellarterm/stellarterm#177]
It might be worthwhile to add the lint now and fix things as we go or make one big PR to address all of the inconsistencies at once. We could also use [prettier](https://github.com/prettier/prettier) to make the code format more consistent.

**Comment by irisli** [comment]
There is linting. I deactivated it because it was creating too many lint errors and messing up travis-ci.

You can improve code style if you want. But I have limited time, and I'm in the business of writing a secure usable product rather than pretty code.

**Comment by janclarin** [comment]
I could look into this later on. Linting helps get rid of dead code, keeps things consistent, and easier to read - especially for other contributors. It might even make bugs easier to discover.

But technically yeah, it doesn't add any immediate value to the project 😜

**Comment by pitsevich** [comment]
Linting is now enabled
