### ISSUE TITLE
Request to add LTZ to your exchange

### ISSUE THREAD

**Issue by litecoinz-project** [stellarterm/stellarterm#254]
Dear stellarterm,

I would like to ask if you could add LitecoinZ to your exchange. LTZ is a quite new cryptocurrency based on Equihash POW algo and it's traded on OctaEx.com.

Here details of LitecoinZ:

WebSite: https://litecoinz.org/
GitHub: https://github.com/litecoinz-project/litecoinz
Discord: https://discord.gg/QNcS4Pm

Best Regards,
Mark

**Comment by tempofr** [comment]
Stellarterm can only be used for stellar based tokens.

**Comment by irisli** [comment]
If you become an anchor on the Stellar network, it can be added to StellarTerm
