### ISSUE TITLE
Inconsistency in Privacy Policy

### ISSUE THREAD

**Issue by zdrive** [stellarterm/stellarterm#265]
There is inconsistent wording in the Privacy Policy, which first states that StellarTerm "does" track clients, and then later says it "does not" track. 

In src/app.jsx:
```
Line 156: <p>StellarTerm does track your actions on this client.</p>
Line 160: <p>While StellarTerm does not track you...</p>
```
I think there's a typo in line 156, but will leave it to the author for clarification.

Thanks

**Comment by irisli** [comment]
oh it's supposed to say "does not". Thanks
