### ISSUE TITLE
REMOVE asset code when removing an offer

### ISSUE THREAD

**Issue by bartekn** [stellarterm/stellarterm#29]
It [looks](https://horizon.stellar.org/operations/43531464934957057) like stellarterm removes the offer using `REMOVE` asset code. Can it used the actual asset that's being removed? It's better for future analysis of the history and looks better in the [dashboard](http://dashboard.stellar.org).

**Comment by irisli** [comment]
Yea it can be doable. It's just more expedient to remove an asset like that.

**Comment by pitsevich** [comment]
Using actual asset codes now
