### ISSUE TITLE
drop down for the known asset classes

### ISSUE THREAD

**Issue by tempofr** [stellarterm/stellarterm#32]
The set pairs work great .. this is a request to easily allow different combinations of the assets.

So if you wanted to trade EURT vs BTC at the top you could type in EURT and BTC and it would fill in the issuer addresses that are already registered in the app. Otherwise copying and pasting the issuer codes is a hassle.

This would allow easier trading of EURT <-> CNY, BTC<->CNY and not all the combilations would have to appear on the list. Just the top ones.

**Comment by irisli** [comment]
Yeah, I need to overhaul the whole UI. Thanks for the suggestions. I will definitely take your suggestions into account.
