### ISSUE TITLE
Cannot Confirm transactions using Ledger Wallet.

### ISSUE THREAD

**Issue by AquaWookie** [stellarterm/stellarterm#406]
Hello support folks!

I'm attempting to conduct a trade AND send KIN from my Ledger Wallet within Stellarterm.

I have the proper amount of the token in the account for the transaction (both sending and trading), when I attempt to conduct the action, it loads tells me to Confirm the transaction on the Ledger Wallet. When I do, it's as though the button input never finds its way to the client.

I've tried numerous times, on both Brave and Chrome- the Ledger itself works as a whole and I can confirm the button is not broken since it's required to input my passcode on the ledger.

No idea why the transactions will not confirm, but because of this I cannot get my KIN off of Stellarterm for its migration swap. I risk losing my entire holdings because this does not work. I've even attempted to sell the KIN to be able to rebuy on another exchange, but because of this bug I cannot sell/trade either (same issue, fails to confirm).

There is no error message, there is no change of the screen/client. It literally just does nothing when I hit confirm. The ledger itself leaves the confirmation screen because it knows I've hit the button, but the Stellarterm client takes no action.

PLEASE HELP! :)

**Comment by little-wave** [comment]
Hello.
We know about this issue, and working on it.
Try to use Opera, or update your ledger firmware and Stellar in network manager on ledger live app.

**Comment by AquaWookie** [comment]
@little-wave I have tried Opera, and am using the newest Ledger Firmware... same issue.

This is horrible, I cannot migrate my KIN, sell my KIN or do anything with it and the clock is ticking on migration ending. I'm potentially going to lose a LOT of money over this bug...

Is there anyone from the development team that can help?

**Comment by pitsevich** [comment]
@AquaWookie Hold tight, we have some ledger improvements coming soon.

And also, your funds are not in Stellarterm, they are on the ledger, so you can use any alternative UI (like [Account Viewer](https://www.stellar.org/account-viewer/)) to access them if it's time sensitive.

**Comment by AquaWookie** [comment]
Outstanding, I've tried to use the Account Viewer before- but the issue is I'm trying to get KIN off a trustline on my Stellar Account. I haven't found a way to do that thus far since I have had to use the apay.io anchor before to send Kin from that account.

**Comment by Schoasch** [comment]
I have the same issue, KIN stuck in a trade, cannot cancel the order

**Comment by pitsevich** [comment]
@AquaWookie @Schoasch
Ledger support should be improved with the latest changes.
Could you try now and let me know if your issues are resolved?

**Comment by Schoasch** [comment]
It is resolved, thank you!

 

Von: Gleb Pitsevich <notifications@github.com> 
Gesendet: Samstag, 4. Mai 2019 10:19
An: stellarterm/stellarterm <stellarterm@noreply.github.com>
Cc: Schoasch <christluxi@web.de>; Mention <mention@noreply.github.com>
Betreff: Re: [stellarterm/stellarterm] Cannot Confirm transactions using Ledger Wallet. (#406)

 

@AquaWookie <https://github.com/AquaWookie>  @Schoasch <https://github.com/Schoasch> 
Ledger support should be improved with the latest changes.
Could you try now and let me know if your issues are resolved?

**Comment by pitsevich** [comment]
Good, closing this issue.

**Comment by AquaWookie** [comment]
I still have not had a chance to confirm this (and will not until my return home from business travel on Monday 5/13) because some rando popped on my thread and declared his issue is resolved does not mean mine (the thread originator) is.

I will notify you if it works or not upon return...

**Comment by pitsevich** [comment]
@AquaWookie Yes, please let us know.
I'm hoping to see another confirmation that it works now.

Please make sure you are using the latest version of Ledger Stellar app though.

**Comment by AquaWookie** [comment]
For sure, will do.

**Comment by AquaWookie** [comment]
@pitsevich, confirmed it now works.

Thanks so much for your help, strong work!
