### ISSUE TITLE
Malware still on Stellarterm website

### ISSUE THREAD

**Issue by Tricky-Ricky** [stellarterm/stellarterm#516]
Topic Originally closed due to a hotfix going out on the 5th of this month...

Navigated to the site and was greeted with said malware again:
https://cdn.discordapp.com/attachments/277762861852262410/601776931205152769/unknown.png

Admittedly - It disappeared this time after awhile, and did not hop around any other windows.

Albeit - Still offputting...

**Comment by pitsevich** [comment]
@Tricky-Ricky Hi Richard,

This has nothing to do with Stellarterm code. There's no malware and this is not a security issue.

Stellarterm has support for "sign in with Ledger", and allows to sign transactions with your Ledger hardware wallet. We use the official Ledger SDK for those purposes.

Windows 10 firewall detects the Ledger device and presents you with this pop-up for some reason.
Ledger devs are aware of this "issue" and maybe will update their SDK.

Here's the relevant information:

https://support.ledger.com/hc/en-us/articles/360023190873-Windows-10-Update-Changes-for-Ledger-Users
https://www.ledger.com/your-ledger-device-and-the-upcoming-windows-10-update/
https://www.reddit.com/r/ledgerwallet/comments/bmg6c2/windows_security_popup_on_windows_may_update/

I will close this issue now.

**Comment by Tricky-Ricky** [comment]
Hi @pitsevich 
Thanks for clarifying - I do not have a Ledger device for it to detect and it acts like malware - Once the pop-up appears you are unable to close the pop-up as it repeats - Tried it again just after this report.

Admittedly if it isn't an issue here, and it is a valid ledger pop-up - Then the SDK needs looking at for sure
