### ISSUE TITLE
Update of Pedity to Tree3 Network

### ISSUE THREAD

**Issue by Pedity-Luffy** [stellarterm/stellarterm#550]
Hi Stellarterm team,
Pedity is now Tree3 Network and would hope to see the name changed on Stellarterm as well.
Kindly advice if a PR is needed.

**Comment by pitsevich** [comment]
Hey, sure - we'll take care of it soon!

**Comment by Pedity-Luffy** [comment]
@pitsevich Hey Gleb, 
Can you please update on this ?

**Comment by pitsevich** [comment]
@Pedity-Luffy Do you plan to change the home domain of this account to tree3.network?

https://stellar.expert/explorer/public/asset/PEDI-GBVUDZLMHTLMZANLZB6P4S4RYF52MVWTYVYXTQ2EJBPBX4DZI2SDOLLY

As I can see, your both domains have similar stellar.toml and suggest ownership of this asset.

https://pedity.com/.well-known/stellar.toml
https://tree3.network/.well-known/stellar.toml

The domain name that we are showing must match the name in the home_domain field.
Your asset is unlocked, so it looks like you could change the home domain

**Comment by Pedity-Luffy** [comment]
@pitsevich Thanks for your response.
The homedomain has been changed to Tree3.Network and details of PEDI Token are also updated on Tree3 Network toml (https://tree3.network/.well-known/stellar.toml).

This will change with launch of new T3 Token as it will be swapped.

**Comment by pitsevich** [comment]
@Pedity-Luffy It's been done now, I'll close this issue.

https://stellarterm.com/exchange/PEDI-tree3.network/XLM-native
