### ISSUE TITLE
Breaking changes in `lightweight-charts`

### ISSUE THREAD

**Issue by timocov** [stellarterm/stellarterm#608]
Hey @little-wave @dmgmyza can you please tell what exactly version 1.1 of `lightweight-charts` breaks for you?

_Originally posted by @timocov in https://github.com/stellarterm/stellarterm/pull/543#issuecomment-527953693_

**Comment by little-wave** [comment]
@timocov hello there. Thanks for your interest.

Problem was with area chart. It was hotfixed with downgrade from 1.0.0 to 1.0.2 as i remember.
Chart isn't drawn only with area type.
Seems like some kind of bug with timeScale params, maybe i missed something, or something changes in docs.

![image](https://user-images.githubusercontent.com/47245891/68663496-d0b06d80-054f-11ea-8efe-0cde540f999a.png)

`
Uncaught Error: Value is null
    at ensureNotNull (lightweight-charts.esm.development.js:103)
    at TimeScaleApi.getVisibleRange (lightweight-charts.esm.development.js:10642)
    at ChartApi._private__onVisibleBarsChanged (lightweight-charts.esm.development.js:10852)
    at lightweight-charts.esm.development.js:1458
    at Array.forEach (<anonymous>)
    at Delegate.fire (lightweight-charts.esm.development.js:1458)
    at TimeScale._private__setVisibleBars (lightweight-charts.esm.development.js:6929)
    at TimeScale._private__updateVisibleBars (lightweight-charts.esm.development.js:6833)
    at TimeScale.visibleBars (lightweight-charts.esm.development.js:6476)
    at TimeScale.setWidth (lightweight-charts.esm.development.js:6505)
`

**Comment by timocov** [comment]
@little-wave Thanks for getting back!

Is it possible to reproduce it now somehow? We really like to fix it (if it's bug) or at least investigate what's going on.

**Comment by little-wave** [comment]
@timocov 
I found a problem. I used the same object type for area & candle & bar, it's work fine for all on versions 1.0.2 and lower.
I used those object for all types of chart.
`{
      "time": 1572822000,
      "close": 0.0638,
      "open": 0.0562,
      "high": 0.0638,
      "low": 0.0624,
  }`

Here is the same code on 1.0.2 and 1.1.0.
It's works with differ object types.
https://jsfiddle.net/syllik/g4jp6e5q/2/

And here is view error
https://jsfiddle.net/syllik/g4jp6e5q/1/

So area chart from 1.0.2 gets like valid value only value field from object data, thats why chart not drawn on upper version.
Also i've noticed that param of timeScale `fixLeftEdge: false` or `fixLeftEdge: true` both didn't fix left edge on versions 1.0.0 or lower. But it seems to have been fixed._

**Comment by timocov** [comment]
@little-wave Sorry for long delay.

> I used the same object type for area & candle & bar, it's work fine for all on versions 1.0.2 and lower.

Ah, I see, we've changed detecting what props we should use for different series' types. In your case you need just convert data from `{open, high, low, close, time}` to `{time, value}` format, because we don't know what exactly value you want to show for line/area series.

> So area chart from 1.0.2 gets like valid value only value field from object data, thats why chart not drawn on upper version.

Yeah, exactly.

> Also i've noticed that param of timeScale fixLeftEdge: false or fixLeftEdge: true both didn't fix left edge on versions 1.0.0 or lower. But it seems to have been fixed.

Looks like it's about this one https://github.com/tradingview/lightweight-charts/issues/144#issuecomment-514987397.

Looks like we don't have any actual bug in lightweight-charts for you, right? If so, I hope we create close this issue for now. Thank you for your time and explanation!

**Comment by little-wave** [comment]
@timocov yeah, i'll fix it with future improvements/updates of our charts.
I think we can close this issue.
