### ISSUE TITLE
Support linking directly to pages with testnet activated

### ISSUE THREAD

**Issue by leighmcculloch** [stellarterm/stellarterm#844]
### What

Support linking directly to pages with testnet activated.

### What happens now

If I go to a URL such as https://stellarterm.com/exchange/COOKIE-GBV4ZEZJXOAW54RKVSIG7XCCY4QOVAQQHJTYKLBM22QMSFUNSV324YFB/XLM-native#testnet with the `#testnet` on the end like the README suggests, the page refreshes and takes me to another page rather than display that URL in testnet mode.

### Why

It's unclear if this is a bug or works as intended. If it works as intended, it would be a useful feature for developers to be able to link directly to a testnet asset.

**Comment by shiny-mountain** [comment]
Already fixed
