### ISSUE TITLE
Stellar term AQUA airdrop error message

### ISSUE THREAD

**Issue by cryptocake3** [stellarterm/stellarterm#985]
I cannot receive my pending AQUA airdrop. It keeps saying memo not set on the Trezor. How can this be fixed in order to get the airdropped coins?

**Comment by shiny-mountain** [comment]
@cryptocake3 problem with Trezor - https://github.com/trezor/trezor-firmware/issues/2274

**Comment by cryptocake3** [comment]
No!
I still cannot get my coins/airdrop...
Why are you saying it is closed!?

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
